################################################################################
# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-file: ../../models/Primary_Detector/resnet10.caffemodel
  proto-file: ../../models/Primary_Detector/resnet10.prototxt
  model-engine-file: ../../models/Primary_Detector/resnet10.caffemodel_b30_gpu0_int8.engine
  labelfile-path: ../../models/Primary_Detector/labels.txt
  int8-calib-file: ../../models/Primary_Detector/cal_trt.bin
  batch-size: 30
  process-mode: 1
  model-color-format: 0
  ## 0=FP32, 1=INT8, 2=FP16 mode
  network-mode: 1
  num-detected-classes: 4
  interval: 0
  gie-unique-id: 1
  output-blob-names: conv2d_bbox;conv2d_cov/Sigmoid
  force-implicit-batch-dim: 1
  #parse-bbox-func-name: NvDsInferParseCustomResnet
  #custom-lib-path: /path/to/libnvdsparsebbox.so
  ## 1=DBSCAN, 2=NMS, 3= DBSCAN+NMS Hybrid, 4 = None(No clustering)
  cluster-mode: 2
  #scaling-filter: 0
  #scaling-compute-hw: 0

#Use the config params below for dbscan clustering mode
#class-attrs-all:
  #detected-min-w: 4
  #detected-min-h: 4
  #minBoxes: 3

#Use the config params below for NMS clustering mode
class-attrs-all:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.2

## Per class configurations
class-attrs-0:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.4

#class-attrs-1:
  #pre-cluster-threshold: 0.05
  #eps: 0.7
  #dbscan-min-score: 0.5

#class-attrs-2:
  #pre-cluster-threshold: 0.1
  #eps: 0.6
  #dbscan-min-score: 0.95

#class-attrs-3:
  #pre-cluster-threshold: 0.05
  #eps: 0.7
  #dbscan-min-score: 0.5
