%YAML:1.0
################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################
# Following properties are mandatory:
#   output-blob-names,  gpu-id,
#   network-type (0-detector, 1-classifier, 2-segmentation)
#
# Mandatory properties for detectors:
#   num-detected-classes
#   labelfile-path
#
# Optional properties for detectors:
#   cluster-mode
#
# Mandatory properties for classifiers:
#   classifier-threshold, is-classifier, classifier-type
#   labelfile-path
#
#  Properties in secondary mode:
#   operate-on-class-ids,
#
# Other optional properties:
#   gie-unique-id(Default=0), process-mode,
#   custom-lib-path, network-mode(Default=0 i.e FP32)
#   class-attrs-all, class-attrs-<class-id>
#
# The values in the config file are overridden by values set through GObject
# properties.


property:
  gpu-id: 0
  process-mode: 1
  num-detected-classes: 4
  gie-unique-id: 1  #Operate on gie-unique-id's output
  ## 1=DBSCAN, 2=NMS, 3= DBSCAN+NMS Hybrid, 4 = None(No clustering)
  cluster-mode: 2
  output-blob-names: conv2d_bbox;conv2d_cov/Sigmoid
  network-type: 0
  labelfile-path: /opt/nvidia/deepstream/deepstream-6.1/samples/models/Primary_Detector/labels.txt

#Use the config params below for dbscan clustering mode
#class-attrs-all:
  #detected-min-w: 4
  #detected-min-h: 4
  #minBoxes: 3

#Use the config params below for NMS clustering mode
class-attrs-all:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.2

## Per class configurations
class-attrs-0:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.2

#class-attrs-1:
  #pre-cluster-threshold: 0.05
  #eps: 0.7
  #dbscan-min-score: 0.5

#class-attrs-2:
  #pre-cluster-threshold: 0.1
  #eps: 0.6
  #dbscan-min-score: 0.95

#class-attrs-3:
  #pre-cluster-threshold: 0.05
  #eps: 0.7
  #dbscan-min-score: 0.5


